### ISSUE TITLE
Unreadable text inputs on Nuxt with TailwindCSS theme

### ISSUE THREAD

**Issue by QuentinLeloire** [vueform/vueform#101]
### Environment

package manager: pnpm 8.12.1
nuxt: 3.8.2
@vueform/nuxt: 1.4.0
@nuxt/ui: 2.11.1
theme: tailwind 3.4.0 (dependency added in lockfile by @nuxt/ui)

### Reproduction

Following fresh install using the official [vueform](https://vueform.com/docs/installation) documentation to implement Vueform on Nuxt with TailwindCSS theme

see sandbox: [here](https://codesandbox.io/p/devbox/gallant-murdock-zxzgqj?file=%2Ftailwind.config.js%3A4%2C32-4%2C39&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqd277qp00073j6fod6siutf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqd277qp00023j6fgd2l4nx5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqd277qp00043j6flkrm5yfz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqd277qp00063j6f32i8jnqp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqd277qp00023j6fgd2l4nx5%2522%253A%257B%2522id%2522%253A%2522clqd277qp00023j6fgd2l4nx5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqd2p7fq00023j6e6o4hx7z8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fvueform%252Fprocess%2522%252C%2522id%2522%253A%2522clqd3cpjs01h83j6ex1sbcysr%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqd3loa900023j6exvj03oe4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A32%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A39%257D%255D%252C%2522filepath%2522%253A%2522%252Ftailwind.config.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqd3loa900023j6exvj03oe4%2522%257D%252C%2522clqd277qp00063j6f32i8jnqp%2522%253A%257B%2522id%2522%253A%2522clqd277qp00063j6f32i8jnqp%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqd32vcc00d23j6ep5oe4l6f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqd32vcc00d23j6ep5oe4l6f%2522%257D%252C%2522clqd277qp00043j6flkrm5yfz%2522%253A%257B%2522id%2522%253A%2522clqd277qp00043j6flkrm5yfz%2522%252C%2522activeTabId%2522%253A%2522clqd2oqpp00nn3j6fwes1g40m%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqd2oqpp00nn3j6fwes1g40m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqd2oqc0000fedeudg7ddxqs%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) or [here](https://codesandbox.io/p/sandbox/gallant-murdock-zxzgqj)

### Describe the bug

In dark mode, text inputs seems to be unreadable by default :

- dark mode
  ![image](https://github.com/vueform/vueform/assets/22280157/9db03a5b-bd33-4c0b-984d-59deae0a84f8)

- light mode
  ![image](https://github.com/vueform/vueform/assets/22280157/b98ece15-dfba-46d1-9197-e75bd21c1fe7)

**Comment by adamberecz** [comment]
With the new [dark mode](https://vueform.com/docs/styles-and-layout#dark-mode) this should now be solved.
