### ISSUE TITLE
Uncaught SyntaxError: ambiguous indirect export: default

### ISSUE THREAD

**Issue by Uninen** [vueform/vueform#103]
### Environment

- Vite 5.0.5
- Tailwind 3.3.5
- pnpm 8.12.1

### Reproduction

https://github.com/Uninen/vueform-pnpm-error-repro

### Describe the bug

First, Thank You for open sourcing VueForm, I hope this project all the best! 🙏 

Following the installation instructions for Vite project + pnpm here: https://vueform.com/docs/installation -- _without shamefully hoisting_ -- VueForm dies with `Uncaught SyntaxError: ambiguous indirect export: default`.

### Additional context

I understand that a bug appearing when not strictly following the installation instructions does not constitute a bug, but in my eyes forcing users to use a highly discouraged practice (of shamefully hoisting) is the bug here.

Vue community has largely adopted pnpm as the default package manager (Vue itself, vue-router, pinia, etc.) and supporting it properly is something that a Vue package should do IMHO. The real reason behind this issue is non-standard/sub-optimal engineering which also makes good TypeScript support hard to do. I hope you consider fixing this issue for all pnpm users.

**Comment by adamberecz** [comment]
Thank you and also for bringing this up. Would you have any recommendation on how to eliminate the need for shamefully hoisting?

**Comment by Uninen** [comment]
I'm not familiar with the internals of this project but I'm sure this can be done. There are plenty of other projects out there for inspiration when you know what to look for. I'm happy to help if I can 👍

**Comment by adamberecz** [comment]
@Uninen `--shameful-hoist` is no longer needed for pnpm install as the themes are now bundled into modules too. Check out our new install guide: https://vueform.com/docs/installation

The only difference should be that it import themes from `dist` and it no longer needs a vite plugin.
