### ISSUE TITLE
Astro Vueform integration issue

### ISSUE THREAD

**Issue by BrentonWheeler** [vueform/vueform#107]
### Environment

"@astrojs/vue": "^4.0.7",
"@vueform/vueform": "^1.6.5",
"astro": "^4.0.9",
"vue": "^3.3.8"

### Reproduction

https://stackblitz.com/edit/github-ewgy71?file=astro.config.mjs,src%2Fpages%2F_app.ts,vueform.config.ts,package.json,README.md

### Describe the bug

I have an issue when trying to follow the [Astro Vue integration docs](https://docs.astro.build/en/guides/integrations-guide/vue/), just wanted to check if I was doing something silly

I've followed this [Vueform doc](https://vueform.com/docs/installation) to try setup the project and I’m hitting the error “Cannot use import statement outside a module”

After checking here: https://publint.dev/@vueform/vueform@1.6.5 it looks like the warning "./dist/index.js is written in ESM, but is interpreted as CJS." could be related to my issue, but I'm not sure what makes this env setup unique enough to cause issues

### Logs

```shell-script
(node:12) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
17:19:43 [ERROR] Cannot use import statement outside a module
  Stack trace:
    at internalCompileFunction (https://githubewgy71-adai.w-credentialless.staticblitz.com/blitz.a2aabdd9.js:180:1005)
    at Module._compile (https://githubewgy71-adai.w-credentialless.staticblitz.com/blitz.a2aabdd9.js:55:14512)
    at Module.load (https://githubewgy71-adai.w-credentialless.staticblitz.com/blitz.a2aabdd9.js:55:13457)
```

**Comment by julisch94** [comment]
Your issue sounds related to my question in the discussions: https://github.com/vueform/vueform/discussions/113

**Comment by BrentonWheeler** [comment]
> Your issue sounds related to my question in the discussions: https://github.com/vueform/vueform/discussions/113

Possibly yeah

**Comment by adamberecz** [comment]
On it! 😎

**Comment by adamberecz** [comment]
A quick update: adding type: "module" to package.json and making the whole library ESM introduces some challenges in testing that I haven't been able to overcome yet.

The `chore/module` branch now contains a version that should work with Astro: https://github.com/vueform/vueform/tree/chore/module

The difference in usage is that you have to include:
- `import vueform from '@vueform/vueform/dist/vueform'` instead of `import vueform from '@vueform/vueform/themes/vueform'` (same for tailwind, etc)
- and `import '@vueform/vueform/dist/vueform.css';` instead of `import '@vueform/vueform/themes/vueform/css/index.min.css';`

(Also, you will no longer need the vite plugin in the future in other envs.)

This is only for testing now, I'll continue digging until I find a solution that can be officially released.

**Comment by adamberecz** [comment]
Finally `1.7.0` is released that should export modules only now.

We also have a new Astro install guide with the steps:
https://vueform.com/docs/installation

I managed to make it work under Astro, let me know if you encounter any issues.

**Comment by BrentonWheeler** [comment]
Resolved, thank you for the great work with the repo and the quick fix 👍

**Comment by preetamslot** [comment]
@BrentonWheeler can you share how you get it working on Astro, when I try to use it I get an error :
https://github.com/vueform/vueform/issues/152

**Comment by BrentonWheeler** [comment]
> @BrentonWheeler can you share how you get it working on Astro, when I try to use it I get an error :
> 
> https://github.com/vueform/vueform/issues/152

You will need to use the client:only directive on the component inside the .astro file

https://docs.astro.build/en/reference/directives-reference/#clientonly

**Comment by preetamslot** [comment]
@BrentonWheeler Thanks for the tip, but my vue component is already `client:only`.
The error is in the theme file `@vueform/vueform/dist/tailwind` loaded in the _app.ts.
Can you share your astro.config _app.ts?

**Comment by preetamslot** [comment]
@BrentonWheeler 
Strange, have the same settings. 

The moment I import a theme, so even without using the components, I get an 'window' error in the theme file.

```
13:47:33 [ERROR] window is not defined
  Hint:
    Browser APIs are not available on the server.

    If the code is in a framework component, try to access these objects after rendering using lifecycle methods or use a `client:only` directive to make the component exclusively run on the client.

    See https://docs.astro.build/en/guides/troubleshooting/#document-or-window-is-not-defined for more information.

  Stack trace:
    at file:///C:/SITES/XXXX/node_modules/@vueform/vueform/dist/vueform.mjs:15975:51
```

**Comment by eslamodeh** [comment]
I have the same issue happening. Any updates regarding this? @preetamslot
