### ISSUE TITLE
Required rule doesn't consider default value 0 with numeric/integer rule

### ISSUE THREAD

**Issue by pagyew** [vueform/vueform#149]
### Environment

@vueform/vueform: 1.8.0
vue: 3.4.20

### Reproduction

https://codesandbox.io/p/devbox/nostalgic-margulis-7s9qwt?file=%2Fsrc%2FApp.vue%3A23%2C21

### Describe the bug

The default value equals 0 is expected to be accepted as a required numeric value, but this is not

### Additional context

If the default value not equals 0 or there are no numeric/integer rules, then everything works as expected

If you change the value and then make it 0 again, then the value is accepted

**Comment by adamberecz** [comment]
Should be now fixed in `1.9.0`.
