### ISSUE TITLE
Value from the numeric input is not number in submitting data

### ISSUE THREAD

**Issue by pagyew** [vueform/vueform#151]
### Environment

@vueform/vueform: 1.8.0
vue: 3.4.20

### Reproduction

https://codesandbox.io/p/devbox/nifty-wiles-pj7z22?file=%2Fsrc%2FApp.vue
Set value in second input manually and submit

### Describe the bug

`form$.data` from numeric inputs is expected to be submit as numbers, but there is not.

This also applies to `form$.requestData`

### Additional context

Default numeric value is submit as a number

**Comment by adamberecz** [comment]
I haven't really thought about converting data type to match input type yet, but I'll think about it.

In the meantime here's a way to force it to `number` when submitting the form:
https://stackblitz.com/edit/github-f96jco?file=src%2FApp.vue

```vue
<TextElement
  name="default1"
  label="Default 1"
  :default="1"
  input-type="number"
  :format-data="(name, value) => ({ [name]: parseInt(value) })"
/>
```

**Comment by pagyew** [comment]
Yeah, thanks for your attention, this is exactly the way I use now 🙂

**Comment by adamberecz** [comment]
`1.9.0` release introduces a new configuration option that converts any `TextElement` value to number if it does not contain anything but a number, `.` or `,`.

It can be applied globally, on form or element level:
https://vueform.com/docs/configuration#forcenumbers
https://vueform.com/reference/vueform#option-force-numbers
https://vueform.com/reference/text-element#option-force-numbers

Hope this solves the issue.

**Comment by pagyew** [comment]
Cool! It works! Thanks for the work you've done!
