### ISSUE TITLE
no infinite property in multiselect element

### ISSUE THREAD

**Issue by hosseinjarrahi** [vueform/vueform#16]
### Environment

latest vite, vue 3

### Reproduction

need reproduction

### Describe the bug

in your multiselect package has a infinite property but in vueform docs, i cant see
and when add infinite prop it does not work

**Comment by adamberecz** [comment]
You can use the `extend-options` prop to add any option which has not been ported to Vueform yet (true for select, multiselect, tags, slider & toggle):
https://vueform.com/reference/multiselect-element#option-extend-options
