### ISSUE TITLE
Using EditorElement throws "The 'data' option should be a function that returns a per-instance value in component definitions."

### ISSUE THREAD

**Issue by everydaysoftware** [vueform/vueform#173]
### Environment

Vue 2.7
Vueform 1.9.0

### Reproduction

`<template>
	<Vueform>
		<EditorElement name="note" label="Note" />
	</Vueform>
</template>
`

### Describe the bug

Using the EditorElement throws the following error

vue.runtime.esm.js:4414 [Vue warn]: The "data" option should be a function that returns a per-instance value in component definitions.

found in

`<EditorWrapper>
       <ElementLayout>
         <EditorElement>
           <FormElements>
             <Vueform>`
...

**Comment by meowwwdev** [comment]
Hey guys

EditorElement in 1.9.10 is not working anymore, i would guess this PR broke it.

How to reproduce: Create a new vueform project and try this code

`
<template>
  <div>
    <Vueform :form-data="formData">
      <EditorElement name="editor"></EditorElement>
      <TextareaElement name="textarea"></TextareaElement>
      <ButtonElement name="submit" submits>Submit</ButtonElement>
    </Vueform>
  </div>
</template>
<script setup lang="ts">
const formData = (form$) => {
  console.log(form$.data)
}
</script>
`

(editor is always null)

could you confirm this issue?

thanks,
Rainer

**Comment by adamberecz** [comment]
Thanks for pointing this out - a patch in `1.9.11` is now released that should fix this issue.

**Comment by meowwwdev** [comment]
updated to 1.9.11 and it works again. thanks @adamberecz
