### ISSUE TITLE
Loading spinner missing when submitting via event

### ISSUE THREAD

**Issue by letmaik** [vueform/vueform#218]
### Environment

"@vueform/vueform": "^1.9.4"

### Reproduction

https://vueform.com/docs/handling-form-data#submit-via-event

### Describe the bug

When following the submit via function method (https://vueform.com/docs/handling-form-data#submit-via-function) then a loading spinner is shown while the async function is in progress. But for the submit via event method, there is no loading spinner.

**Comment by letmaik** [comment]
I found out that I have to manually do `form$.submitting = true` and `form$.submitting = false`. If that's expected I would extend the example in the docs.

**Comment by adamberecz** [comment]
Thanks for pointing this out. I've revisited the example code the `Submit via Event` case:
https://vueform.com/docs/handling-form-data#submit-via-event
