### ISSUE TITLE
 NUXT ERROR: Failed to resolve import "/.nuxt/vueformPlugin.mjs"

### ISSUE THREAD

**Issue by Ryan-santos** [vueform/vueform#22]
### Environment

node 20.9.0
npm 10.1.0
Nuxt 3.8.1
theme vueform

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mlfffm

### Describe the bug

When attempting to add modules to my project, I am encountering the following errors:

1. **Compilation Error:**
   ```
   ERROR  Could not compile template vueformPlugin.mjs.
   ```

2. **Path Resolution Warnings:**
   ```
   WARN  Could not resolve /.nuxt/vueformPlugin.mjs.
   WARN  Could not resolve /.nuxt/vueformPlugin.mjs.
   WARN  Could not resolve /.nuxt/vueformPlugin.mjs.
   ```

*Translated from Portuguese (pt-BR).*

**Comment by adamberecz** [comment]
Thanks for reporting this @Ryan-santos - it seems like something has changed in Nuxt that caused the error. We released a patch for `@vueform/nuxt` so if you upgrade to `1.3.0` it should be work now.
