### ISSUE TITLE
Extra vertical space added when hidden element is used

### ISSUE THREAD

**Issue by msizenko** [vueform/vueform#23]
### Environment

- vue: ^3.2.31
- @vueform/vueform: ^1.5.4
- vite: ^4.5.0
- @vitejs/plugin-vue: ^4.4.0
- theme: Vueform

### Reproduction

Minimal reproduction available here:
[https://codesandbox.io/p/sandbox/ecstatic-water-h5lpvr](https://codesandbox.io/p/sandbox/ecstatic-water-h5lpvr?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cloymde1j00063b5xd37jsw3b%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cloymde1i00033b5xrrmnzro5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloymde1i00043b5xgd0faqy9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloymde1i00053b5xhkvfvdac%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cloymde1i00033b5xrrmnzro5%2522%253A%257B%2522id%2522%253A%2522cloymde1i00033b5xrrmnzro5%2522%252C%2522activeTabId%2522%253A%2522cloymlfo500hk3b5xhl0cn64u%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloymde1h00023b5xsdkcylkh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FMyForm.vue%2522%252C%2522id%2522%253A%2522cloymlfo500hk3b5xhl0cn64u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.js%2522%252C%2522id%2522%253A%2522cloymohl702w73b5xd0kucn69%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522cloymde1i00053b5xhkvfvdac%2522%253A%257B%2522id%2522%253A%2522cloymde1i00053b5xhkvfvdac%2522%252C%2522activeTabId%2522%253A%2522cloymdkzf004l3b5xmije7zys%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cloymdkzf004l3b5xmije7zys%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cloymde1i00043b5xgd0faqy9%2522%253A%257B%2522id%2522%253A%2522cloymde1i00043b5xgd0faqy9%2522%252C%2522activeTabId%2522%253A%2522cloymdj4a003n3b5xyzp42cso%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cloymdj4a003n3b5xyzp42cso%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Describe the bug

`hidden` element adds extra vertical space between the form fields.

### Additional context

<img width="673" alt="Screenshot 2023-11-14 at 18 11 08" src="https://github.com/vueform/vueform/assets/702316/bccfcb2b-b378-46c3-a6c1-089e784c0c36">

**Comment by adamberecz** [comment]
If you don't need an actual hidden input (which will result in this), I'd recommend using [`meta: true`](https://vueform.com/reference/hidden-element#option-meta).
