### ISSUE TITLE
Failed to create project with Vite: spawn pnpm ENOENT

### ISSUE THREAD

**Issue by ssw1992** [vueform/vueform#238]
### Environment

Windows 10 专业版 22H2
11th Gen Intel(R) Core(TM) i7-1165G7

### Reproduction

最新版，window环境试试

### Describe the bug

执行pnpm create vueform创建项目
最后一步创建执行，报错Failed to create project with Vite: spawn pnpm ENOENT
用npm就报Failed to create project with Vite: spawn npm ENOENT，
用yarn就报Failed to create project with Vite: spawn yarn ENOENT
不同操作系统差异导致，能否兼容

**Comment by adamberecz** [comment]
Thanks for reporting the issue. A fix has been [released](https://github.com/vueform/create-vueform/releases) - please update `create-vueform` to `1.0.12` (or run `npm create vueform@latest`) and try again.
