### ISSUE TITLE
Only Vite platform is selectable when creating a new project (via npm create vueform)

### ISSUE THREAD

**Issue by sldev2** [vueform/vueform#257]
### Environment

I tried with npm, yarn, and pnpm. (didn't try with Bun).

I am looking to create a Nuxt project, which is visible as an option, but is not selectable.

### Reproduction

try running : npm create vueform@latest -- --builder --publicKey={your key}

### Describe the bug

arrow down key doesn't work, so only Vite is selectable

**Comment by adamberecz** [comment]
Which OS, node and npm version are you using?
