### ISSUE TITLE
`PhoneElement` does not detect changes

### ISSUE THREAD

**Issue by Ryan-santos** [vueform/vueform#280]
#### System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 3.60 GB / 15.84 GB
   #### Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
   #### Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
  ####  npmPackages:
    @vueform/nuxt: ^1.6.0 => 1.6.0
    @vueform/plugin-mask: ^1.0.7 => 1.0.7
    nuxt: ^3.12.3 => 3.12.3
    vue: ^3.4.21 => 3.4.31

### Reproduction

https://stackblitz.com/edit/github-y6fhmj?file=src%2FApp.vue

### Describe the bug

When the value of the `PhoneElement` is changed via `v-model` in the form, it does not trigger change events or update the state correctly. It seems that the component is not watching for changes as expected.

**Comment by adamberecz** [comment]
It's indeed a bug. Reproduction: https://stackblitz.com/edit/github-wyqbzj?file=src%2FApp.vue,vueform.config.js
