### ISSUE TITLE
forceNumbers doesn't apply for TextElement in ObjectElement schemas

### ISSUE THREAD

**Issue by Nezertiam** [vueform/vueform#285]
### Environment

Vite 5.2.11 / tailwind / npm

### Reproduction

https://stackblitz.com/edit/vitejs-vite-yc1mxc?file=src%2FApp.vue

### Describe the bug

`forceNumbers` property works perfectly fine if the `TextElement` is located at the top level of the schema. However, when nesting it inside an `ObjectElement`, the property doesn't apply and the data has the value stored as a string.

### Additional context

It seems it also does it with `GroupElement`.

**Comment by jadrake75** [comment]
Great to see fixed.  I was running on 1.9.12 and couldn't figure out why forceNumbers in some of my forms was not working but trying to create a simplified use-case was working.  This was the reason.  I can verify it is working for me in 1.10.4+
