### ISSUE TITLE
The domain you've reached includes a version of Vueform without permission.

### ISSUE THREAD

**Issue by Sakthi002** [vueform/vueform#3]

**Comment by adamberecz** [comment]
This means that either you're trying to use Vueform on a live domain without a paid license or the domain is not added properly to your whitelist or the package has not been updated in your project after refreshing the whitelist.

**Comment by Sakthi002** [comment]
How to check the trial version - i want to check all the functionalities before purchasing - form and form builder

**Comment by adamberecz** [comment]
You can test it only on `localhost`.

**Comment by Sakthi002** [comment]
Okay - Thank you
