### ISSUE TITLE
Nested Vueform in GroupElement triggers error when using validation

### ISSUE THREAD

**Issue by menno-rdmkr** [vueform/vueform#302]
### Environment

Vite: v5.3.5
Vueform: 1.10.3

### Reproduction

[https://stackblitz.com/edit/github-qiu3za?file=src%2FApp.vue](https://stackblitz.com/edit/github-qiu3za?file=src%2FApp.vue)

```TS
<template>
  <Vueform ref="form$">
    <GroupElement name="test">
      <Vueform ref="form2$">
        <TextElement name="text" :rules="['required']" />
      </Vueform>
    </GroupElement>
  </Vueform>
</template>
```

### Describe the bug

When embedding a `Vueform` in another `Vueform` with validation-rules in the embedded `Vueform`, everything works as expected, so no errors.

But as soon as I place the embedded `Vueform` in a `GroupElement` and I add validation-rules to my `TextElement`, i get the following error:

```@vueform_vueform.js?v=49cef486:11431 Uncaught 
TypeError: Cannot read properties of null (reading 'messages')
    at new Validator (@vueform_vueform.js?v=49cef486:11431:43)
    at new required (@vueform_vueform.js?v=49cef486:14389:16)
    at Proxy.make (@vueform_vueform.js?v=49cef486:12398:12)
    at @vueform_vueform.js?v=49cef486:12390:19
    at arrayMap$6 (@vueform_vueform.js?v=49cef486:8265:22)
    at map2 (@vueform_vueform.js?v=49cef486:11361:10)
    at Proxy.makeAll (@vueform_vueform.js?v=49cef486:12389:12)
    at Object.initValidation (@vueform_vueform.js?v=49cef486:23623:33)
    at @vueform_vueform.js?v=49cef486:22398:12
    at chunk-WV4RVYET.js?v=ba159074:3033:40```

### Additional context

_No response_

### Logs

_No response_

**Comment by Layenzz** [comment]
That's not only inside that. 

I added an addon on TextElement & TextAreaElement (who contains a component who's instantiate a new Vueform inside this component and i have exactly the same error)

**Comment by adamberecz** [comment]
@menno-rdmkr — this isn't a bug, you aren't supposed to put a `<Vueform>` component into a `<GroupElement>` that's only to contain other elements.

You can put `<Vueform>` in a `<Vueform>` component though.

@Layenzz — that sounds like a different issue. Please create a separate issue for it with a reproduction.
