### ISSUE TITLE
Can still edit rich text editor when disabled

### ISSUE THREAD

**Issue by Tim-Wapenaar-Fenetre** [vueform/vueform#325]
### Environment

Found on 
Builder: 1.4.4
Vueform: 1.10.3

Checked on https://builder.vueform.com/demo
Builder: 1.6.5
Vueform: 1.10.3

### Reproduction

https://builder.vueform.com/demo

### Describe the bug

1. Add a WYSIWYG editor to the form
2. Add a default value
3. Disable the element
4. Preview the form
5. Select the text
6. Use the styling buttons at the top of the element

The styling of the text still changes, and the value of the data still changes.

---
1. Add a WYSIWYG editor element to the form builder
2. Add a default value
3. Disable the element
4. Reload the page
5. Preview the form
6. Click between the letters text
8. Start typing

New text gets added and also changes the value in the data.

---
This also happens with Vueform not just the builder preview

**Comment by adamberecz** [comment]
Thanks for reporting the issue. Fixed in `1.10.5`
