### ISSUE TITLE
Form OFF Display settings don't work

### ISSUE THREAD

**Issue by dan-dazlab** [vueform/vueform#350]
### Environment

    "@vitejs/plugin-vue": "^5.1.4",
    "@vueform/builder": "^1.8.0",
    "@vueform/vueform": "1.10.3",
    "autoprefixer": "^10.4.20",
    "html2pdf.js": "https://github.com/eKoopmans/html2pdf.js.git",
    "postcss": "^8.4.33",
    "resize-observer-polyfill": "^1.5.1",
    "sass": "^1.80.5",
    "signature_pad": "^5.0.4",
    "tailwindcss": "^3.4.14",
    "vite": "^5.4.1",
    "vue": "^3.5.12"

### Reproduction

<img width="319" alt="image" src="https://github.com/user-attachments/assets/81d281af-9797-49ef-9637-888b1d62420c">

### Describe the bug

<img width="854" alt="image" src="https://github.com/user-attachments/assets/8f4af92b-b08f-4df8-9bcb-0540565ac178">

On submit with not filled required fields I still see messages on the top of the form.

**Comment by adamberecz** [comment]
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/e29cf261-af40-43cd-9aae-bf0753366f04">

I could not reproduce this. Feel free to reopen with a [reproduction](https://stackblitz.com/github/vueform/builder-sandbox) link.
