### ISSUE TITLE
Don't clear hidden elements

### ISSUE THREAD

**Issue by anhaabaete** [vueform/vueform#352]
### Environment

Hi!

When I create a form, the ID hidden input is null.
After I send the form, I want clear it, to a new send a new register.
So, at a first moment I used ....formvue.clear() and after reset etc.
But nothing remove value of id hidden input.

So tried form..$el(#).update('').... clear()... reset()...

And nothing.... :/

Why it's happen?

### Reproduction

1 - Using scheme, create a form at least one Hidden element named ID
2 - Fill the form and send it, and dont out of compoment
3 - Only try clear it

4 - Use the inspect element to see. The hidden elemento dont update.

### Describe the bug

When I create a form, the ID hidden input is null.
After I send the form, I want clear it, to a new send a new register.
So, at a first moment I used ....formvue.clear() and after reset etc.
But nothing remove value of id hidden input.

### Additional context

I'm load a component to create e form to register some data

### Logs

```shell-script
Without logs
```

**Comment by adamberecz** [comment]
I wasn't able to reproduce this so I'm closing this. Feel free to reopen with a [reproduction](https://stackblitz.com/github/vueform/sandbox).
