### ISSUE TITLE
Matrix-Element with dynamic rows deletes content if row is added

### ISSUE THREAD

**Issue by everydaysoftware** [vueform/vueform#368]
### Environment

Vue 2.7
@vueform/vueform": "^1.11.0

Your Builder environment
Examples in your component description

### Reproduction

https://builder.vueform.com/demo
https://vueform.com/reference/matrix-element

### Describe the bug

Add matrix element with dynamic rows

`vueform: {
      schema: {
        matrix: {
          type: 'matrix',
          cols: [
            {
              label: 'Column 1',
              value: 'column_1',
              inputType: {
                type: 'text',
                inputType: 'number',
                autocomplete: 'off',
                forceNumbers: true,
              },
            },
            {
              label: 'Column 2',
              value: 'column_2',
              inputType: {
                type: 'text',
              },
            },
          ],
          rows: 1,
          presets: [
            'matrix-table',
          ],
        },
      },
    }`

Fill out first row then add new row. 
All values will be deleted.

![vueform-matrix-1](https://github.com/user-attachments/assets/e39b7988-bd57-420e-8779-613328baac47)

![vueform-matrix-2](https://github.com/user-attachments/assets/0503b936-5cd7-4ba7-ba43-c4ca1b879d8b)

**Comment by adamberecz** [comment]
Thanks for reporting the issue. A hot-fix is release in `1.11.1`.

**Comment by everydaysoftware** [comment]
Thank you a lot! Could you push 1.11.1 to NPM? It is still on 1.11.0

**Comment by adamberecz** [comment]
Oops, you're right—[there](https://www.npmjs.com/package/@vueform/vueform/v/1.11.1) it is.
