### ISSUE TITLE
The requested module '/node_modules/wnumb/wNumb.js?v=c0698822' does not provide an export named 'default' (at useTooltip.js:2:8)

### ISSUE THREAD

**Issue by alexsignly** [vueform/vueform#5]
I'm trying to integrate this into my Vue3+Vite project get the following error every single time:

Uncaught SyntaxError: The requested module '/node_modules/wnumb/wNumb.js?v=c0698822' does not provide an export named 'default' (at useTooltip.js:2:8)

I also tried creating a fresh Vue3 + Vite and follow your installation steps (from the logged in are) but still no luck.

Do you have any suggestion?

**Comment by adamberecz** [comment]
Have you tried using our installation wizard? https://vueform.com/docs/1.x/installation

Vite requires an extra step of adding some libs to optimizeDeps. The basic `vite.config.js` should look like this:

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: {
        compilerOptions: {
          isCustomElement: (tag) => ['trix-editor'].indexOf(tag) !== -1
        }
      },
    }),
  ],
  optimizeDeps: {
    include: [
      'nouislider',
      'wnumb',
      'trix'
    ]
  }
})
```

**Comment by adamberecz** [comment]
Thanks @pscheit , but these should not be required anymore - instead we have a Vite plugin that contains everything that needs to be added to `vite.config.js`.

**Comment by pscheit** [comment]
oooh! i missed this in the setup guide, cause i clicked on vue. Thanks!
