### ISSUE TITLE
Issue Report: Unexpected Checkbox Group Behavior in VueForm Form Builder

### ISSUE THREAD

**Issue by yllberisha** [vueform/vueform#6]
# Issue Report: Unexpected Checkbox Group Behavior in VueForm Form Builder

## Description:
When using the VueForm form builder component, the checkbox groups exhibit unintended behavior by selecting all options when choosing just one. This behavior contradicts the expected functionality of independent checkbox selections.

### Steps to Reproduce:

1. Visit the example URL: https://vueform.com/examples/basics/form-builder
2. Observe the checkbox groups in the form.
3. Attempt to select a single option within any checkbox group.

### Expected Behavior:
Checkbox groups should allow individual options to be selected without automatically selecting others in the same group. Each checkbox should function independently.

### Actual Behavior:
Upon selecting a single checkbox option within a group, all other options in that group are simultaneously selected. The preview JSON data also reflects this, with all options in the group set to true.

## Additional Notes:

This behavior compromises accurate data collection within the form, particularly for checkbox groups.
A short video clip demonstrating the issue is included: 

https://github.com/vueform/vueform/assets/102769384/8f7695de-96d5-4d7d-a70e-4e73aca92f69

**Comment by yllberisha** [comment]
Hello everyone,

I'd like to share an update on the checkbox group issue I reported. After analyzing the problem, I've pinpointed the cause and found a solution that resolves the unexpected behavior.

The issue stemmed from an error in the inline code generation, specifically in rendering the preview of questions. I've corrected this by adjusting the key used for dynamically generated components. Now, each checkbox group functions independently, allowing individual selections without affecting others.

Here's the corrected code snippet for reference:

```diff
-:name="i"
+:name="question.type"
```

I've tested the solution, and the checkbox groups now behave as expected, ensuring accurate data collection.

Your feedback is appreciated. Thank you for your attention.

----------------------
Here the the entire code:
```vue

<template>
  <form class="max-w-lg w-full">
    <FormTabs>
      <FormTab
        name="questions"
        label="Questions"
        :elements="['questions']"
      />
      <FormTab
        name="preview"
        label="Preview"
        :elements="['preview']"
      />
    </FormTabs>
    <FormElements>

      <!-- Questions -->
      <ListElement
        name="questions"
        add-text="+"
        :sort="true"
        :override-classes="{
          ListElement: {
            add: 'bg-green-500 w-10 h-10 text-white flex items-center justify-center text-xl font-bold mx-auto rounded-full',
            add_md: '',
          }
        }"
      >
        <template #default="{ index }">

          <!-- One question -->
          <ObjectElement
            :name="index"
            add-class="mb-4"
            :override-classes="{
              ElementLayout: {
                outerWrapper: 'flex flex-wrap',
                innerWrapper: 'bg-white rounded-lg py-8 px-10 shadow-box-circle',
              }
            }"
          >
            <!-- Question title -->
            <StaticElement name="title">
              <div class="text-xl mb-4 font-semibold">Question {{ index + 1 }}</div>
            </StaticElement>

            <!-- Question -->
            <TextElement
              name="label"
              placeholder="Question"
            />

            <!-- Question description -->
            <TextareaElement
              name="description"
              placeholder="Description"
            />

            <!-- Answer type -->
            <SelectElement
              name="type"
              default="text"
              label="Type"
              :items="[
                'text', 'textarea', 'select', 'checkboxgroup', 'radiogroup'
              ]"
            />

            <!-- Answer options (if any) -->
            <ListElement
              name="items"
              label="Options"
              add-text="+ Add option"
              :conditions="[
                ['questions.*.type', ['select', 'checkboxgroup', 'radiogroup']]
              ]"
            >
              <template #default="{ index }">
                <TextElement :name="index" />
              </template>
            </ListElement>
          </ObjectElement>
        </template>
      </ListElement>

      <!-- Question preview -->
      <ObjectElement
        name="preview"
        add-class="w-full"
        :override-classes="{
          ElementLayout: {
            outerWrapper: 'flex flex-wrap',
            innerWrapper: 'bg-white rounded-lg py-8 px-10 shadow-box-circle',
          }
        }"
      >
        <component
          v-for="question, i in questions"
          :is="`${question.type}-element`" 
```     
```diff
-:name="i"
+:name="question.type"
```
```javascript

          :label="question.label"
          :description="question.description"
          :items="question.items"
          :key="i"
        />
      </ObjectElement>
    </FormElements>
  </form>
</template>
```

**Comment by adamberecz** [comment]
Hey, thanks for reporting and proposing the solution. We'll look into it.

**Comment by adamberecz** [comment]
Got it fixed with **:name="`${i}-${question.type}`"** otherwise you could've only have one from each type ;)
