### ISSUE TITLE
VueForm fails to render multilingual forms with localized default values

### ISSUE THREAD

**Issue by djkunkel** [vueform/vueform#94]
### Environment

Vite 5.0.4
Vue 2.7.15
VueForm 1.6.4

### Reproduction

1. Create a builder application with multiple locales.
2. Create a form in that builder with Text and Hidden with default values defined for each language.
3. Export the form and use with with VueForm with locales enabled.
4. Note that you get an exception in the console
```Invalid prop: type check failed for prop "default". Expected String, Number, got Object found in <HiddenElement>```

See example here:
https://stackblitz.com/edit/vitejs-vite-lq5dsv?file=App.vue

### Describe the bug

It seems that the Hidden and Text elements expect a simple string and don't accept the localized object with multiple locales.

**Comment by adamberecz** [comment]
Thanks for reporting the issue. Fixed in `1.6.5`.
